package com.revature.streams.optional;


import java.util.Optional;

import static com.revature.streams.optional.OptionalBasics.average;

/*
 * Common Instance methods for Optional
 * get() : Throws a NoSuchElementException if the Optional is empty, otherwise returns the Optional value.
 *
 * isPresent() : Returns false if the optional is empty, otherwise returns true if there is a value.
 *
 * ifPresent(Consumer c) : Performs actions using the supplied Consumer, otherwise skips the operation if
 * 						the Optional is empty.
 *
 * orElse(T other) : If the Optional is empty, returns the supplied argument value.
 * 					Otherwise returns the Optional value.
 *
 * orElseGet(Supplier s) : If the Optional is empty, returns the value generated by the supplier argument.
 * 					Otherwise returns the Optional value.
 *
 * orElseThrow() : If the Optional is empty, throws a NoSuchElementException, otherwise returns the Optional value.
 *
 * orElseThrow(Supplier s) : If the Optional is empty, throws a throwable generated by the Supplier argument.
 * 					Otherwise returns the Optional value.
 */
public class OptionalMethods {
    public static void main(String[] args) throws MyCustomException {

        Optional<Double> o1 = average();
        if (o1.isPresent()) System.out.println(o1.get());

        Optional<Double> o2 = average();
        o2.ifPresent(x ->
                System.out.println(x)
        );
        o2.ifPresent(System.out::println);



        Optional<Double> o3 = average();
        System.out.println( o3.orElse(Double.valueOf(100)) );
        /*
            variable = methodCall;
            if (variable != null)
                do something
            else
                do something else
         */





        Optional<Double> o4 = average();
        System.out.println( o4.orElseGet(() -> Math.random()) );
        // alternatively: System.out.println( o4.orElseGet(Math::random) );

        Optional<Double> o5 = average();
        System.out.println( o5.orElseThrow() );

        Optional<Double> o6 = average();
        System.out.println( o6.orElseThrow( () -> new MyCustomException()) );
        // alternatively :  System.out.println( o6.orElseThrow(MyCustomException::new) );
    }
}

class MyCustomException extends Exception { }
