spring.application.name=expanded

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/trng2464
spring.datasource.username=joe
spring.datasource.password=password
spring.jpa.properties.hibernate.default_schema=examples

management.endpoints.web.exposure.include=health, info, metrics, env, beans
info.app.name=Employee Management API
info.app.description=Training Example API for managing Employees, Paychecks and Login details
info.app.version=1.0.0
management.endpoint.health.show-details=always

# The following properties are for logging setup
logging.file.name=logs/app.log

# This pattern sets a rolling Daily rolling policy
# Note: Logback's underlying policy class always requires %i in the
# pattern whenever max-file-size is set. This %i is used to indicate
# a numeric count if the max-file-size is ever reached.
logging.logback.rollingpolicy.file-name-pattern=logs/app.%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=1GB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=3GB
logging.logback.rollingpolicy.clean-history-on-start=true

# The following removes the Spring banner from printing to the console
spring.main.banner-mode=off

# You can set a Root logging level
logging.level.root=warn

# You can override the level for everything under a specific package:
logging.level.com.revature.expanded.logging=info

# Or you can override the level for a single class
# logging.level.com.revature.expanded.logging.LoggingAspect=info
