spring.application.name=basics

# This is redundant since auto-restart is enabled by default
spring.devtools.restart.enabled=true

# Enable LiveReload
spring.devtools.livereload.enabled=true

# This is to support Spring Boot Starter Web
server.port=8080

# Datasource Configuration - To support Spring Boot Starter Data JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/trng2464
spring.datasource.username=joe
spring.datasource.password=password

# Note: I am explicitly stating the schema across my entities, but
#       I could have configured it here with the following line:
# spring.jpa.properties.hibernate.default_schema=examples


# Actuator Endpoint Configuration
# When opting into endpoints, you should avoid use of the wildcard in
# favor of explicitly named endpoints.
management.endpoints.web.exposure.include=health, info, metrics, env, beans

# Additional configurations
info.app.name=Employee Management API
info.app.description=Training Example API for managing Employees, Paychecks and Login details
info.app.version=1.0.0

# The following enables more details than just 'UP/DOWN' status
management.endpoint.health.show-details=always